CREATE TABLE IF NOT EXISTS PRICES (
  "ID" BIGINT NOT NULL AUTO_INCREMENT,
  "BRAND_ID" INTEGER NOT NULL,
  "CURR" VARCHAR(3) NOT NULL,
  "END_DATE" TIMESTAMP WITH TIME ZONE NOT NULL,
  "FEE_ID" INTEGER NOT NULL,
  "PRICE" DOUBLE NOT NULL,
  "PRIORITY" INTEGER NOT NULL,
  "PRODUCT_ID" BIGINT NOT NULL,
  "START_DATE" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("ID")
);